name: Release
on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.19.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Run Semantic Release
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang }}
      - name: Cache Go modules
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/cache@v3.3.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.golang }}-v1-
      - name: Run GoReleaser
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
